import { GlAccountSeed } from '@/types/accounts';

export const SYSCOHADA_CLASS_6: GlAccountSeed[] = [
  { code: '6', name: 'Comptes de charges des activités ordinaires' },

  { code: '60', name: 'Achats et variations de stocks' },
  { code: '601', name: 'Achat de marchandises' },
  { code: '602', name: 'Achat de matières premières et fournitures liées' },
  { code: '604', name: 'Achat stocké de matières et fournitures consommables' },
  { code: '6042', name: 'Carburant et lubrifiant' },
  { code: '6043', name: 'Produits d’entretien' },
  { code: '605', name: 'Autres achats' },
  { code: '6051', name: 'Eau' },
  { code: '6052', name: 'Électricité' },
  { code: '6055', name: 'Fournitures de bureau' },
  { code: '6056', name: 'Achats de petit matériel et outillages' },
  { code: '608', name: 'Achats d’emballages' },
  { code: '6081', name: 'Emballages perdus' },
  { code: '6085', name: 'Frais sur achat (douane, fret, assurance, commission, courtage, transit…)' },

  { code: '61', name: 'Transports' },
  { code: '612', name: 'Transports sur ventes' },
  { code: '614', name: 'Transports du personnel' },
  { code: '618', name: 'Autres frais de transports' },
  { code: '6181', name: 'Voyages et déplacements' },

  { code: '62', name: 'Services extérieurs' },
  { code: '622', name: 'Locations, charges locatives' },
  { code: '6222', name: 'Location de bâtiments' },
  { code: '6223', name: 'Locations de matériels et outillages' },
  { code: '624', name: 'Entretien, réparation, remise en état et maintenance' },
  { code: '6241', name: 'Entretien et réparation biens immobiliers' },
  { code: '6242', name: 'Entretien et réparation des biens mobiliers' },
  { code: '625', name: 'Primes d’assurances' },
  { code: '6252', name: 'Assurances matériel de transport' },
  { code: '6258', name: 'Autres primes d’assurance' },
  { code: '628', name: 'Frais de télécommunication' },
  { code: '6281', name: 'Frais de téléphone' },
  { code: '6288', name: 'Autres frais de télécommunication' },

  { code: '63', name: 'Autres services extérieurs' },
  { code: '631', name: 'Frais bancaires' },
  { code: '632', name: 'Rémunérations d’intermédiaires et des conseils' },
  { code: '6324', name: 'Honoraires des professions réglementées' },
  { code: '6325', name: 'Frais d’actes et de contentieux' },
  { code: '633', name: 'Frais de formation du personnel' },
  { code: '637', name: 'Rémunérations de personnel extérieur à l’entité' },
  { code: '6371', name: 'Personnel intérimaire' },
  { code: '6372', name: 'Personnel détaché ou prêté à l’entité' },
  { code: '638', name: 'Autres charges externes' },
  { code: '6382', name: 'Frais de déménagement' },
  { code: '6383', name: 'Réception' },
  { code: '6384', name: 'Missions' },
  { code: '6385', name: 'Charges de copropriété' },
  { code: '6388', name: 'Charges externes diverses' },

  { code: '64', name: 'Impôts et taxes' },
  { code: '641', name: 'Impôts et taxes directes' },
  { code: '6411', name: 'Impôts fonciers et taxes annexes' },
  { code: '6412', name: 'Patentes, licences et taxes annexes' },
  { code: '6418', name: 'Autres impôts et taxes directes' },
  { code: '645', name: 'Impôts et taxes indirectes' },
  { code: '646', name: 'Droits d’enregistrement' },
  { code: '6461', name: 'Droit de mutation' },
  { code: '6463', name: 'Taxes sur véhicules de sociétés' },
  { code: '6464', name: 'Vignettes' },
  { code: '6468', name: 'Autres droits d’enregistrement (Go pass…)' },
  { code: '647', name: 'Pénalités, amendes fiscales' },

  { code: '65', name: 'Autres charges' },
  { code: '651', name: 'Pertes sur créances clients et autres débiteurs' },
  { code: '6511', name: 'Clients' },
  { code: '6515', name: 'Autres débiteurs' },
  { code: '656', name: 'Perte de change sur créances et dettes commerciales' },
  { code: '657', name: 'Pénalités et amendes pénales' },
  { code: '658', name: 'Charges diverses' },
  { code: '6582', name: 'Dons' },
  { code: '6583', name: 'Mécénat' },
  { code: '6588', name: 'Autres charges diverses' },

  { code: '66', name: 'Charges du personnel' },
  { code: '661', name: 'Rémunérations directes versées au personnel national' },
  { code: '664', name: 'Charges sociales' },
  { code: '666', name: 'Rémunérations et charges sociales de l’exploitant individuel' },
  { code: '6661', name: 'Rémunérations du travail de l’exploitant' },
  { code: '6662', name: 'Charges sociales' },
  { code: '668', name: 'Autres charges sociales' },

  { code: '68', name: 'Dotations aux amortissements' },
  { code: '681', name: 'Dotations aux amortissements d’exploitation' },
  { code: '6812', name: 'Dotations aux amortissements des immobilisations incorporelles' },
  { code: '6813', name: 'Dotations aux amortissements des immobilisations corporelles' }
];
